# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b518964d3178562d495bf3885e81a1c205c17319c1cfe2a8c23d80e002944d4502d5dfcc34c63ce4a47bd3dab2bb8ea122cfb2624d2a7f38e3c8b66c3e67cb03

test:
  secret_key_base: 61a59119525d4550ca6499b3a7d438bd131af57613ec3b093cc753542ada557333e4b38c2d0aa631d1d4ece130f754c81e2d98c656d483151aa0ca6a6d3da044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
